Shift Correction and Plotting Updates
AxelHenningsson/darling pull request #1
Opened 2024-11-20 09:33 UTC by adcret

### Update: Shift Correction and Mosaicity Mapping Improvements

---

#### **Shift Correction**
I have integrated the shift correction method developed by Felix. Currently, this implementation works **only between rocking curves**, but I am working on generalizing it. 

I also experimented with **Numba** to see if I could figure it out, and it appears to be working for me. I'm using it to shift the images.

---

#### **Plotting**
- **Mosaicity Mapping Updates**:
  - Updated the code to use **motor values** as limits for both the colormap and image normalization.
  - This change resolves issues with regions of zeros in the images where no data was present (e.g., ranges like `-7` to `-9` previously caused problems see example 1).

- **Improved Visualization**:
  - **Blue Channel Adjustment**: Reduced the blue channel to `0.75`, which makes it easier to visualize the data by minimizing overly white pixels. (see example 2)

  Examples:
  ![Mosaicity Example 1](https://github.com/user-attachments/assets/f0431d83-2d10-4039-a5ed-b53a776bfb67)
  ![Mosaicity Example 2](https://github.com/user-attachments/assets/54938607-0d1b-43d4-a784-ebf0410a6755)

- **Masking Feature**:
  - Added an **optional mask input** to the mosaicity maps and covariance maps.
  - This allows plotting only the data **within the mask**, providing a cleaner plots.

---

2024-11-22 06:17 UTC, AxelHenningsson commented
Fantastic Adam! :heart: I will review this during the day.

I am working on getting pytest to run with github actions upon push and pull requests, such that we can atumatically know if any new changes breaks the code. :sunglasses: 

Cheers
Axel Henningsson

2024-11-22 08:01 UTC, AxelHenningsson requested changes
I am very happy :heart:   that you have taken the time to work on progressing this library. :+1: 

I have gone over all the code and provided comments. :slightly_smiling_face: 

Please do not be dissmayed, I can be a tad thourough. :see_no_evil: 

General comments:

* The code needs to integrate with existing unit tests, either by changing the tests, or by changing the code.
 
* Any newly added features needs unit testing following the standard of darling.

* Finally, the PR needs to pass with a clean pytest before it can be merged. You 
 could run these on your own machine to start with. The idea is that they will also run on the remote servers upon PR and push such that all reviewers can see that the PR does not break any code.
   
   
* I suggest the possible inclusion of examples following the sphinx docstring convention. I have written a parser that will parse for docstring examples executing them with pytest to ensure they run.

* I suggest we stick with the black code style. https://github.com/psf/black. This can be installed  in most editors and autoformat everything you got with a button-press. So no real extra work.

* A comment for the future: It will be good if any one single PR is only about one single change. I.e break down the upgrades into the minimal pecies that are standalone. For instance, shift correction and modifications to the _Vizualizer could be two seperate PRs.
 
 Again, thanks a lot for chipping in on this one. :rocket: :+1: 
 
 Cheers
 Axel

2024-11-24 19:31 UTC, adcret commented
Thank you very much Axel I really appreciate you taking the time to comment thoroughly. I'll look through them and make the necessary changes either this evening or tomorrow.  

Adam

2024-12-07 20:05 UTC, AxelHenningsson commented
Any luck finding the time to work on this?

Best,
Axel

2025-01-06 12:19 UTC, closed without merging